name: Experiment
# on: 
#   schedule:
#   - cron: '0 */1 * * *'
on: [push]

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: prepare current repository into runner
      uses: actions/checkout@v2
    - name: check github actions environment variables
      run: env
    - name: show runner environment variables
      run: printenv
    - name: show github workspace directory content
      run: ls -al $GITHUB_WORKSPACE
    - name: show readme content
      run: cat ./README.md
