name: Experiment
# on: 
#   schedule:
#   - cron: '*/5 * * * *'
on: [push]

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Every time
      run: echo "This step will always run"
