name: Experiment
# on: 
#   schedule:
#   - cron: '0 */1 * * *'
on: [push]

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: prepare current repository into runner
      uses: actions/checkout@v2
    - name: Check environment variables
      run: env
    - name: show github workspace directory content and current working directory
      run: ls -al $GITHUB_WORKSPACE & pwd
    - name: show readme content
      run: cat ./README.md
